/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stonehiy_opencv_OpenCVHelper */

#ifndef _Included_com_stonehiy_opencv_OpenCVHelper
#define _Included_com_stonehiy_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stonehiy_opencv_OpenCVHelper
 * Method:    getStringTmp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stonehiy_opencv_OpenCVHelper_getStringTmp
  (JNIEnv *, jclass);

/*
 * Class:     com_stonehiy_opencv_OpenCVHelper
 * Method:    getGrayImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_stonehiy_opencv_OpenCVHelper_getGrayImage
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
